// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file slotpb/pharaohtreasure.proto (package pharaohtreasure, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file slotpb/pharaohtreasure.proto.
 */
export const file_slotpb_pharaohtreasure: GenFile = /*@__PURE__*/
  fileDesc("ChxzbG90cGIvcGhhcmFvaHRyZWFzdXJlLnByb3RvEg9waGFyYW9odHJlYXN1cmUiIwoTUGhhcmFvaHRyZWFzdXJlQ2VsbBIMCgRzeW1iGAEgASgJQscBChNjb20ucGhhcmFvaHRyZWFzdXJlQhRQaGFyYW9odHJlYXN1cmVQcm90b1ABWj5naXRodWIuY29tL3NreXJvY2tldC1xeS9zbG90L2ludGVybmFsL3N2Yy9zbG90L3BoYXJhb2h0cmVhc3VyZaICA1BYWKoCD1BoYXJhb2h0cmVhc3VyZcoCD1BoYXJhb2h0cmVhc3VyZeICG1BoYXJhb2h0cmVhc3VyZVxHUEJNZXRhZGF0YeoCD1BoYXJhb2h0cmVhc3VyZWIGcHJvdG8z");

/**
 * @generated from message pharaohtreasure.PharaohtreasureCell
 */
export type PharaohtreasureCell = Message<"pharaohtreasure.PharaohtreasureCell"> & {
  /**
   * @generated from field: string symb = 1;
   */
  symb: string;
};

/**
 * Describes the message pharaohtreasure.PharaohtreasureCell.
 * Use `create(PharaohtreasureCellSchema)` to create a new message.
 */
export const PharaohtreasureCellSchema: GenMessage<PharaohtreasureCell> = /*@__PURE__*/
  messageDesc(file_slotpb_pharaohtreasure, 0);

