// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file slotpb/princesssun.proto (package princesssun, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file slotpb/princesssun.proto.
 */
export const file_slotpb_princesssun: GenFile = /*@__PURE__*/
  fileDesc("ChhzbG90cGIvcHJpbmNlc3NzdW4ucHJvdG8SC3ByaW5jZXNzc3VuIh8KD1ByaW5jZXNzc3VuQ2VsbBIMCgRzeW1iGAEgASgJQqsBCg9jb20ucHJpbmNlc3NzdW5CEFByaW5jZXNzc3VuUHJvdG9QAVo6Z2l0aHViLmNvbS9za3lyb2NrZXQtcXkvc2xvdC9pbnRlcm5hbC9zdmMvc2xvdC9wcmluY2Vzc3N1bqICA1BYWKoCC1ByaW5jZXNzc3VuygILUHJpbmNlc3NzdW7iAhdQcmluY2Vzc3N1blxHUEJNZXRhZGF0YeoCC1ByaW5jZXNzc3VuYgZwcm90bzM");

/**
 * @generated from message princesssun.PrincesssunCell
 */
export type PrincesssunCell = Message<"princesssun.PrincesssunCell"> & {
  /**
   * @generated from field: string symb = 1;
   */
  symb: string;
};

/**
 * Describes the message princesssun.PrincesssunCell.
 * Use `create(PrincesssunCellSchema)` to create a new message.
 */
export const PrincesssunCellSchema: GenMessage<PrincesssunCell> = /*@__PURE__*/
  messageDesc(file_slotpb_princesssun, 0);

