// api.proto

// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file slotpb/slot.proto (package slotpb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file slotpb/slot.proto.
 */
export const file_slotpb_slot: GenFile = /*@__PURE__*/
  fileDesc("ChFzbG90cGIvc2xvdC5wcm90bxIGc2xvdHBiIjAKBUV2ZW50EgwKBGNvZGUYASABKA0SDAoEZGF0YRgCIAEoDBILCgN3aW4YAyABKA0iJAoFVGFibGUSGwoFcmVlbHMYASADKAsyDC5zbG90cGIuUmVlbCIXCgRSZWVsEg8KB3N5bWJvbHMYASADKAkiGwoDUG9zEgkKAXgYASABKAUSCQoBeRgCIAEoBSJICgdTcGluUmVxEg8KB2dhbWVfaWQYASABKA0SEQoEb21lbhgCIAEoDEgAiAEBEhAKCHN0cmF0ZWd5GAMgASgJQgcKBV9vbWVuIlIKCFNwaW5SZXNwEh0KBmV2ZW50cxgBIAMoCzINLnNsb3RwYi5FdmVudBILCgN3aW4YAiABKA0SEQoEb21lbhgDIAEoDEgAiAEBQgcKBV9vbWVuIiEKBkJpZ1N5bRIKCgJpZBgBIAEoDRILCgNsZW4YAiABKA0yOAoLU2xvdFNlcnZpY2USKQoEU3BpbhIPLnNsb3RwYi5TcGluUmVxGhAuc2xvdHBiLlNwaW5SZXNwQoEBCgpjb20uc2xvdHBiQglTbG90UHJvdG9QAVowZ2l0aHViLmNvbS9za3lyb2NrZXQtcXkvcHJvdG9zL2dlbi9zbG90cGI7c2xvdHBiogIDU1hYqgIGU2xvdHBiygIGU2xvdHBi4gISU2xvdHBiXEdQQk1ldGFkYXRh6gIGU2xvdHBiYgZwcm90bzM");

/**
 * @generated from message slotpb.Event
 */
export type Event = Message<"slotpb.Event"> & {
  /**
   * @generated from field: uint32 code = 1;
   */
  code: number;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;

  /**
   * @generated from field: uint32 win = 3;
   */
  win: number;
};

/**
 * Describes the message slotpb.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_slotpb_slot, 0);

/**
 * @generated from message slotpb.Table
 */
export type Table = Message<"slotpb.Table"> & {
  /**
   * @generated from field: repeated slotpb.Reel reels = 1;
   */
  reels: Reel[];
};

/**
 * Describes the message slotpb.Table.
 * Use `create(TableSchema)` to create a new message.
 */
export const TableSchema: GenMessage<Table> = /*@__PURE__*/
  messageDesc(file_slotpb_slot, 1);

/**
 * @generated from message slotpb.Reel
 */
export type Reel = Message<"slotpb.Reel"> & {
  /**
   * @generated from field: repeated string symbols = 1;
   */
  symbols: string[];
};

/**
 * Describes the message slotpb.Reel.
 * Use `create(ReelSchema)` to create a new message.
 */
export const ReelSchema: GenMessage<Reel> = /*@__PURE__*/
  messageDesc(file_slotpb_slot, 2);

/**
 * @generated from message slotpb.Pos
 */
export type Pos = Message<"slotpb.Pos"> & {
  /**
   * @generated from field: int32 x = 1;
   */
  x: number;

  /**
   * @generated from field: int32 y = 2;
   */
  y: number;
};

/**
 * Describes the message slotpb.Pos.
 * Use `create(PosSchema)` to create a new message.
 */
export const PosSchema: GenMessage<Pos> = /*@__PURE__*/
  messageDesc(file_slotpb_slot, 3);

/**
 * @generated from message slotpb.SpinReq
 */
export type SpinReq = Message<"slotpb.SpinReq"> & {
  /**
   * @generated from field: uint32 game_id = 1;
   */
  gameId: number;

  /**
   * @generated from field: optional bytes omen = 2;
   */
  omen?: Uint8Array;

  /**
   * @generated from field: string strategy = 3;
   */
  strategy: string;
};

/**
 * Describes the message slotpb.SpinReq.
 * Use `create(SpinReqSchema)` to create a new message.
 */
export const SpinReqSchema: GenMessage<SpinReq> = /*@__PURE__*/
  messageDesc(file_slotpb_slot, 4);

/**
 * @generated from message slotpb.SpinResp
 */
export type SpinResp = Message<"slotpb.SpinResp"> & {
  /**
   * @generated from field: repeated slotpb.Event events = 1;
   */
  events: Event[];

  /**
   * @generated from field: uint32 win = 2;
   */
  win: number;

  /**
   * @generated from field: optional bytes omen = 3;
   */
  omen?: Uint8Array;
};

/**
 * Describes the message slotpb.SpinResp.
 * Use `create(SpinRespSchema)` to create a new message.
 */
export const SpinRespSchema: GenMessage<SpinResp> = /*@__PURE__*/
  messageDesc(file_slotpb_slot, 5);

/**
 * @generated from message slotpb.BigSym
 */
export type BigSym = Message<"slotpb.BigSym"> & {
  /**
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * @generated from field: uint32 len = 2;
   */
  len: number;
};

/**
 * Describes the message slotpb.BigSym.
 * Use `create(BigSymSchema)` to create a new message.
 */
export const BigSymSchema: GenMessage<BigSym> = /*@__PURE__*/
  messageDesc(file_slotpb_slot, 6);

/**
 * @generated from service slotpb.SlotService
 */
export const SlotService: GenService<{
  /**
   * @generated from rpc slotpb.SlotService.Spin
   */
  spin: {
    methodKind: "unary";
    input: typeof SpinReqSchema;
    output: typeof SpinRespSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_slotpb_slot, 0);

