// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file wallet/wallet.proto (package wallet, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file wallet/wallet.proto.
 */
export const file_wallet_wallet: GenFile = /*@__PURE__*/
  fileDesc("ChN3YWxsZXQvd2FsbGV0LnByb3RvEgZ3YWxsZXQqQwoKV2FsbGV0VHlwZRIbChdXQUxMRVRfVFlQRV9VTlNQRUNJRklFRBAAEgoKBkxPQ0tFRBABEgwKCFVOTE9DS0VEEAIqfgoGVHhUeXBlEhcKE1RYX1RZUEVfVU5TUEVDSUZJRUQQABILCgdERVBPU0lUEAESBwoDQkVUEAISBwoDV0lOEAMSDwoLQVVDVElPTl9CVVkQBBIQCgxBVUNUSU9OX1NFTEwQBRIHCgNUQVgQBhIQCgxBRE1JTl9BREpVU1QQB0KFAQoKY29tLndhbGxldEILV2FsbGV0UHJvdG9QAVoyZ2l0aHViLmNvbS9za3lyb2NrZXQtcXkvcHJvdG9zL2dlbi93YWxsZXQ7d2FsbGV0cGKiAgNXWFiqAgZXYWxsZXTKAgZXYWxsZXTiAhJXYWxsZXRcR1BCTWV0YWRhdGHqAgZXYWxsZXRiBnByb3RvMw");

/**
 * @generated from enum wallet.WalletType
 */
export enum WalletType {
  /**
   * @generated from enum value: WALLET_TYPE_UNSPECIFIED = 0;
   */
  WALLET_TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: LOCKED = 1;
   */
  LOCKED = 1,

  /**
   * @generated from enum value: UNLOCKED = 2;
   */
  UNLOCKED = 2,
}

/**
 * Describes the enum wallet.WalletType.
 */
export const WalletTypeSchema: GenEnum<WalletType> = /*@__PURE__*/
  enumDesc(file_wallet_wallet, 0);

/**
 * @generated from enum wallet.TxType
 */
export enum TxType {
  /**
   * @generated from enum value: TX_TYPE_UNSPECIFIED = 0;
   */
  TX_TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: DEPOSIT = 1;
   */
  DEPOSIT = 1,

  /**
   * @generated from enum value: BET = 2;
   */
  BET = 2,

  /**
   * @generated from enum value: WIN = 3;
   */
  WIN = 3,

  /**
   * @generated from enum value: AUCTION_BUY = 4;
   */
  AUCTION_BUY = 4,

  /**
   * @generated from enum value: AUCTION_SELL = 5;
   */
  AUCTION_SELL = 5,

  /**
   * @generated from enum value: TAX = 6;
   */
  TAX = 6,

  /**
   * @generated from enum value: ADMIN_ADJUST = 7;
   */
  ADMIN_ADJUST = 7,
}

/**
 * Describes the enum wallet.TxType.
 */
export const TxTypeSchema: GenEnum<TxType> = /*@__PURE__*/
  enumDesc(file_wallet_wallet, 1);

