// @generated by buffa-codegen. DO NOT EDIT.

include!("authzpb.rbacpb.rbac.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("authzpb.rbacpb.rbac.__view.rs");
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__GET_ROLE_IN_JSON_ANY);
        reg.register_json_any(super::__GET_ROLE_OUT_JSON_ANY);
        reg.register_json_any(super::__PERMISSION_JSON_ANY);
        reg.register_json_any(super::__LIST_RESOURCE_TYPE_OUT_JSON_ANY);
        reg.register_json_any(super::__LIST_RESOURCES_BY_TYPE_IN_JSON_ANY);
        reg.register_json_any(super::__LIST_RESOURCES_BY_TYPE_OUT_JSON_ANY);
        reg.register_json_any(super::__LIST_RESOURCES_BY_TYPE_DATA_JSON_ANY);
        reg.register_json_any(super::__LIST_PERMISSION_BY_RESOURCE_IN_JSON_ANY);
        reg.register_json_any(super::__LIST_PERMISSION_BY_RESOURCE_OUT_JSON_ANY);
        reg.register_json_any(super::__USER_JSON_ANY);
        reg.register_json_any(super::__UPDATE_USER_IN_JSON_ANY);
        reg.register_json_any(super::__ROLE_JSON_ANY);
        reg.register_json_any(super::__RESOURCE_JSON_ANY);
        reg.register_json_any(super::__LIST_USERS_IN_JSON_ANY);
        reg.register_json_any(super::__LIST_USERS_OUT_JSON_ANY);
        reg.register_json_any(super::__DELETE_USER_IN_JSON_ANY);
        reg.register_json_any(super::__CREATE_ROLE_IN_JSON_ANY);
        reg.register_json_any(super::__LIST_ROLES_IN_JSON_ANY);
        reg.register_json_any(super::__LIST_ROLES_OUT_JSON_ANY);
        reg.register_json_any(super::__UPDATE_ROLE_IN_JSON_ANY);
        reg.register_json_any(super::__DELETE_ROLE_IN_JSON_ANY);
        reg.register_json_any(super::__LIST_RESOURCES_IN_JSON_ANY);
        reg.register_json_any(super::__LIST_RESOURCES_OUT_JSON_ANY);
        reg.register_json_any(super::__CREATE_RESOURCE_IN_JSON_ANY);
        reg.register_json_any(super::__DELETE_RESOURCE_IN_JSON_ANY);
        reg.register_json_any(super::__ASSIGN_ROLE_IN_JSON_ANY);
        reg.register_json_any(super::__REVOKE_ROLE_IN_JSON_ANY);
        reg.register_json_any(super::__GRANT_PERM_IN_JSON_ANY);
        reg.register_json_any(super::__REVOKE_PERM_IN_JSON_ANY);
    }
}
#[doc(inline)]
pub use self::__buffa::view::GetRoleInView;
#[doc(inline)]
pub use self::__buffa::view::GetRoleOutView;
#[doc(inline)]
pub use self::__buffa::view::PermissionView;
#[doc(inline)]
pub use self::__buffa::view::ListResourceTypeOutView;
#[doc(inline)]
pub use self::__buffa::view::ListResourcesByTypeInView;
#[doc(inline)]
pub use self::__buffa::view::ListResourcesByTypeOutView;
#[doc(inline)]
pub use self::__buffa::view::ListResourcesByTypeDataView;
#[doc(inline)]
pub use self::__buffa::view::ListPermissionByResourceInView;
#[doc(inline)]
pub use self::__buffa::view::ListPermissionByResourceOutView;
#[doc(inline)]
pub use self::__buffa::view::UserView;
#[doc(inline)]
pub use self::__buffa::view::UpdateUserInView;
#[doc(inline)]
pub use self::__buffa::view::RoleView;
#[doc(inline)]
pub use self::__buffa::view::ResourceView;
#[doc(inline)]
pub use self::__buffa::view::ListUsersInView;
#[doc(inline)]
pub use self::__buffa::view::ListUsersOutView;
#[doc(inline)]
pub use self::__buffa::view::DeleteUserInView;
#[doc(inline)]
pub use self::__buffa::view::CreateRoleInView;
#[doc(inline)]
pub use self::__buffa::view::ListRolesInView;
#[doc(inline)]
pub use self::__buffa::view::ListRolesOutView;
#[doc(inline)]
pub use self::__buffa::view::UpdateRoleInView;
#[doc(inline)]
pub use self::__buffa::view::DeleteRoleInView;
#[doc(inline)]
pub use self::__buffa::view::ListResourcesInView;
#[doc(inline)]
pub use self::__buffa::view::ListResourcesOutView;
#[doc(inline)]
pub use self::__buffa::view::CreateResourceInView;
#[doc(inline)]
pub use self::__buffa::view::DeleteResourceInView;
#[doc(inline)]
pub use self::__buffa::view::AssignRoleInView;
#[doc(inline)]
pub use self::__buffa::view::RevokeRoleInView;
#[doc(inline)]
pub use self::__buffa::view::GrantPermInView;
#[doc(inline)]
pub use self::__buffa::view::RevokePermInView;
#[doc(inline)]
pub use self::__buffa::register_types;
