// @generated by buffa-codegen. DO NOT EDIT.

include!("authzpb.v1.authz.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("authzpb.v1.authz.__view.rs");
        pub mod oneof {
            #[allow(unused_imports)]
            use super::*;
            include!("authzpb.v1.authz.__view_oneof.rs");
        }
    }
    pub mod oneof {
        #[allow(unused_imports)]
        use super::*;
        include!("authzpb.v1.authz.__oneof.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::CheckInView;
#[doc(inline)]
pub use self::__buffa::view::CheckOutView;
#[doc(inline)]
pub use self::__buffa::view::TupleView;
#[doc(inline)]
pub use self::__buffa::view::TupleFilterView;
#[doc(inline)]
pub use self::__buffa::view::ListTuplesInView;
#[doc(inline)]
pub use self::__buffa::view::ListTuplesOutView;
#[doc(inline)]
pub use self::__buffa::view::InstanceView;
#[doc(inline)]
pub use self::__buffa::view::TreeNodeView;
#[doc(inline)]
pub use self::__buffa::view::DeleteTuplesInView;
#[doc(inline)]
pub use self::__buffa::view::DeleteTuplesView;
#[doc(inline)]
pub use self::__buffa::view::DeleteTupleIdsView;
#[doc(inline)]
pub use self::__buffa::view::GraphUpdateView;
#[doc(inline)]
pub use self::__buffa::view::GraphUpdateTupleView;
