// @generated by buffa-codegen. DO NOT EDIT.

include!("fishpb.fish.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("fishpb.fish.__view.rs");
        pub mod oneof {
            #[allow(unused_imports)]
            use super::*;
            include!("fishpb.fish.__view_oneof.rs");
        }
    }
    pub mod oneof {
        #[allow(unused_imports)]
        use super::*;
        include!("fishpb.fish.__oneof.rs");
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__SUBSCRIBE_REQUEST_JSON_ANY);
        reg.register_json_any(super::__JOIN_REQUEST_JSON_ANY);
        reg.register_json_any(super::__JOIN_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__SHOOT_REQUEST_JSON_ANY);
        reg.register_json_any(super::__SHOOT_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__HIT_REQUEST_JSON_ANY);
        reg.register_json_any(super::__HIT_RESULT_JSON_ANY);
        reg.register_json_any(super::__HIT_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__LEAVE_REQUEST_JSON_ANY);
        reg.register_json_any(super::__LEAVE_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__FRAME_MESSAGE_JSON_ANY);
        reg.register_json_any(super::__FRAME_EVENT_JSON_ANY);
        reg.register_json_any(super::__MACHINE_PLAYER_ENTERED_JSON_ANY);
        reg.register_json_any(super::__MACHINE_PLAYER_EXITED_JSON_ANY);
        reg.register_json_any(super::__MACHINE_PLAYER_FIRED_JSON_ANY);
        reg.register_json_any(super::__MACHINE_PLAYER_CATCHED_JSON_ANY);
        reg.register_json_any(super::__MACHINE_PLAYER_UPDATED_JSON_ANY);
        reg.register_json_any(super::__SCENE_UPDATED_JSON_ANY);
        reg.register_json_any(super::__TARGET_CREATED_JSON_ANY);
        reg.register_json_any(super::__TARGET_SETTING_ODDS_JSON_ANY);
        reg.register_json_any(super::__TARGET_JSON_ANY);
        reg.register_json_any(super::__BULLET_JSON_ANY);
    }
}
#[doc(inline)]
pub use self::__buffa::view::SubscribeRequestView;
#[doc(inline)]
pub use self::__buffa::view::JoinRequestView;
#[doc(inline)]
pub use self::__buffa::view::JoinResponseView;
#[doc(inline)]
pub use self::__buffa::view::ShootRequestView;
#[doc(inline)]
pub use self::__buffa::view::ShootResponseView;
#[doc(inline)]
pub use self::__buffa::view::HitRequestView;
#[doc(inline)]
pub use self::__buffa::view::HitResultView;
#[doc(inline)]
pub use self::__buffa::view::HitResponseView;
#[doc(inline)]
pub use self::__buffa::view::LeaveRequestView;
#[doc(inline)]
pub use self::__buffa::view::LeaveResponseView;
#[doc(inline)]
pub use self::__buffa::view::FrameMessageView;
#[doc(inline)]
pub use self::__buffa::view::FrameEventView;
#[doc(inline)]
pub use self::__buffa::view::MachinePlayerEnteredView;
#[doc(inline)]
pub use self::__buffa::view::MachinePlayerExitedView;
#[doc(inline)]
pub use self::__buffa::view::MachinePlayerFiredView;
#[doc(inline)]
pub use self::__buffa::view::MachinePlayerCatchedView;
#[doc(inline)]
pub use self::__buffa::view::MachinePlayerUpdatedView;
#[doc(inline)]
pub use self::__buffa::view::SceneUpdatedView;
#[doc(inline)]
pub use self::__buffa::view::TargetCreatedView;
#[doc(inline)]
pub use self::__buffa::view::TargetSettingOddsView;
#[doc(inline)]
pub use self::__buffa::view::TargetView;
#[doc(inline)]
pub use self::__buffa::view::BulletView;
#[doc(inline)]
pub use self::__buffa::register_types;
