// @generated by buffa-codegen. DO NOT EDIT.
// source: pkgpb/v1/pkg.proto

pub mod filter_node {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Node {
        Filter(::buffa::alloc::boxed::Box<super::super::super::Filter>),
        Logical(::buffa::alloc::boxed::Box<super::super::super::Logical>),
    }
    impl ::buffa::Oneof for Node {}
    impl From<super::super::super::Filter> for Node {
        fn from(v: super::super::super::Filter) -> Self {
            Self::Filter(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::Filter> for ::core::option::Option<Node> {
        fn from(v: super::super::super::Filter) -> Self {
            Self::Some(Node::from(v))
        }
    }
    impl From<super::super::super::Logical> for Node {
        fn from(v: super::super::super::Logical) -> Self {
            Self::Logical(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::Logical> for ::core::option::Option<Node> {
        fn from(v: super::super::super::Logical) -> Self {
            Self::Some(Node::from(v))
        }
    }
}
