// @generated by buffa-codegen. DO NOT EDIT.
// source: slotpb/slot_extra_data.proto

pub mod arthur {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, Debug)]
    pub enum Data<'a> {
        Fg(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ArthurFgView<'a>,
            >,
        ),
        Bg(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ArthurBgView<'a>,
            >,
        ),
        Sbg(
            ::buffa::alloc::boxed::Box<
                super::super::super::super::__buffa::view::ArthurBgView<'a>,
            >,
        ),
    }
}
