// @generated by buffa-codegen. DO NOT EDIT.

include!("walletpb.wallet.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("walletpb.wallet.__view.rs");
    }
    /// Register this package's `Any` type entries and extension entries.
    pub fn register_types(reg: &mut ::buffa::type_registry::TypeRegistry) {
        reg.register_json_any(super::__GET_BALANCE_REQUEST_JSON_ANY);
        reg.register_json_any(super::__GET_BALANCE_RESPONSE_JSON_ANY);
        reg.register_json_any(super::__UPDATE_BALANCE_REQUEST_JSON_ANY);
        reg.register_json_any(super::__UPDATE_BALANCE_RESPONSE_JSON_ANY);
    }
}
#[doc(inline)]
pub use self::__buffa::view::GetBalanceRequestView;
#[doc(inline)]
pub use self::__buffa::view::GetBalanceResponseView;
#[doc(inline)]
pub use self::__buffa::view::UpdateBalanceRequestView;
#[doc(inline)]
pub use self::__buffa::view::UpdateBalanceResponseView;
#[doc(inline)]
pub use self::__buffa::register_types;
