// api.proto

// @generated by protoc-gen-es v2.6.3
// @generated from file gatewaypb/v1/gateway.proto (package gatewaypb.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file gatewaypb/v1/gateway.proto.
 */
export const file_gatewaypb_v1_gateway = /*@__PURE__*/
  fileDesc("ChpnYXRld2F5cGIvdjEvZ2F0ZXdheS5wcm90bxIMZ2F0ZXdheXBiLnYxIkMKDkdhdGVXYXlSZXF1ZXN0EhIKCnJlcXVlc3RfaWQYASABKAkSEAoIb3BlX2NvZGUYAiABKA0SCwoDbXNnGAMgASgMIjIKD0dhdGVXYXlSZXNwb25zZRISCgpyZXF1ZXN0X2lkGAEgASgJEgsKA21zZxgCIAEoDDJaCg5HYXRlV2F5U2VydmljZRJICgdHYXRlV2F5EhwuZ2F0ZXdheXBiLnYxLkdhdGVXYXlSZXF1ZXN0Gh0uZ2F0ZXdheXBiLnYxLkdhdGVXYXlSZXNwb25zZSIAQq4BChBjb20uZ2F0ZXdheXBiLnYxQgxHYXRld2F5UHJvdG9QAVo7Z2l0aHViLmNvbS9za3lyb2NrZXQtcXkvcHJvdG9zL2dlbi9nYXRld2F5cGIvdjE7Z2F0ZXdheXBidjGiAgNHWFiqAgxHYXRld2F5cGIuVjHKAgxHYXRld2F5cGJcVjHiAhhHYXRld2F5cGJcVjFcR1BCTWV0YWRhdGHqAg1HYXRld2F5cGI6OlYxYgZwcm90bzM");

/**
 * Describes the message gatewaypb.v1.GateWayRequest.
 * Use `create(GateWayRequestSchema)` to create a new message.
 */
export const GateWayRequestSchema = /*@__PURE__*/
  messageDesc(file_gatewaypb_v1_gateway, 0);

/**
 * Describes the message gatewaypb.v1.GateWayResponse.
 * Use `create(GateWayResponseSchema)` to create a new message.
 */
export const GateWayResponseSchema = /*@__PURE__*/
  messageDesc(file_gatewaypb_v1_gateway, 1);

/**
 * @generated from service gatewaypb.v1.GateWayService
 */
export const GateWayService = /*@__PURE__*/
  serviceDesc(file_gatewaypb_v1_gateway, 0);

