// @generated by protoc-gen-es v2.6.3 with parameter "target=ts"
// @generated from file bastionpb/bastion.proto (package bastionpb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Event } from "../slotpb/slot_pb";
import { file_slotpb_slot } from "../slotpb/slot_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bastionpb/bastion.proto.
 */
export const file_bastionpb_bastion: GenFile = /*@__PURE__*/
  fileDesc("ChdiYXN0aW9ucGIvYmFzdGlvbi5wcm90bxIJYmFzdGlvbnBiIkAKCVdTUmVxdWVzdBIOCgZhY3Rpb24YASABKAkSDwoHcGF5bG9hZBgCIAEoDBISCgpyZXF1ZXN0X2lkGAMgASgJInMKCldTUmVzcG9uc2USDgoGYWN0aW9uGAEgASgJEg8KB3BheWxvYWQYAiABKAwSEgoKcmVxdWVzdF9pZBgDIAEoCRImCgVlcnJvchgEIAEoCzISLmJhc3Rpb25wYi5XU0Vycm9ySACIAQFCCAoGX2Vycm9yIk4KC1NwaW5SZXF1ZXN0Eg8KB2dhbWVfaWQYASABKA0SEgoKYmV0X2Ftb3VudBgCIAEoDRIRCgRvbWVuGAMgASgMSACIAQFCBwoFX29tZW4iKQoIU3BpblJlc3ASHQoGZXZlbnRzGAEgAygLMg0uc2xvdHBiLkV2ZW50IiIKDEJ1eUZnUmVxdWVzdBISCgpiZXRfYW1vdW50GAEgASgNIioKCUJ1eUZnUmVzcBIdCgZldmVudHMYASADKAsyDS5zbG90cGIuRXZlbnQiKAoHV1NFcnJvchIMCgRjb2RlGAEgASgJEg8KB21lc3NhZ2UYAiABKAlCmQEKDWNvbS5iYXN0aW9ucGJCDEJhc3Rpb25Qcm90b1ABWjZnaXRodWIuY29tL3NreXJvY2tldC1xeS9wcm90b3MvZ2VuL2Jhc3Rpb25wYjtiYXN0aW9ucGKiAgNCWFiqAglCYXN0aW9ucGLKAglCYXN0aW9ucGLiAhVCYXN0aW9ucGJcR1BCTWV0YWRhdGHqAglCYXN0aW9ucGJiBnByb3RvMw", [file_slotpb_slot]);

/**
 * @generated from message bastionpb.WSRequest
 */
export type WSRequest = Message<"bastionpb.WSRequest"> & {
  /**
   * @generated from field: string action = 1;
   */
  action: string;

  /**
   * @generated from field: bytes payload = 2;
   */
  payload: Uint8Array;

  /**
   * @generated from field: string request_id = 3;
   */
  requestId: string;
};

/**
 * Describes the message bastionpb.WSRequest.
 * Use `create(WSRequestSchema)` to create a new message.
 */
export const WSRequestSchema: GenMessage<WSRequest> = /*@__PURE__*/
  messageDesc(file_bastionpb_bastion, 0);

/**
 * @generated from message bastionpb.WSResponse
 */
export type WSResponse = Message<"bastionpb.WSResponse"> & {
  /**
   * @generated from field: string action = 1;
   */
  action: string;

  /**
   * @generated from field: bytes payload = 2;
   */
  payload: Uint8Array;

  /**
   * @generated from field: string request_id = 3;
   */
  requestId: string;

  /**
   * @generated from field: optional bastionpb.WSError error = 4;
   */
  error?: WSError;
};

/**
 * Describes the message bastionpb.WSResponse.
 * Use `create(WSResponseSchema)` to create a new message.
 */
export const WSResponseSchema: GenMessage<WSResponse> = /*@__PURE__*/
  messageDesc(file_bastionpb_bastion, 1);

/**
 * @generated from message bastionpb.SpinRequest
 */
export type SpinRequest = Message<"bastionpb.SpinRequest"> & {
  /**
   * @generated from field: uint32 game_id = 1;
   */
  gameId: number;

  /**
   * @generated from field: uint32 bet_amount = 2;
   */
  betAmount: number;

  /**
   * @generated from field: optional bytes omen = 3;
   */
  omen?: Uint8Array;
};

/**
 * Describes the message bastionpb.SpinRequest.
 * Use `create(SpinRequestSchema)` to create a new message.
 */
export const SpinRequestSchema: GenMessage<SpinRequest> = /*@__PURE__*/
  messageDesc(file_bastionpb_bastion, 2);

/**
 * @generated from message bastionpb.SpinResp
 */
export type SpinResp = Message<"bastionpb.SpinResp"> & {
  /**
   * @generated from field: repeated slotpb.Event events = 1;
   */
  events: Event[];
};

/**
 * Describes the message bastionpb.SpinResp.
 * Use `create(SpinRespSchema)` to create a new message.
 */
export const SpinRespSchema: GenMessage<SpinResp> = /*@__PURE__*/
  messageDesc(file_bastionpb_bastion, 3);

/**
 * @generated from message bastionpb.BuyFgRequest
 */
export type BuyFgRequest = Message<"bastionpb.BuyFgRequest"> & {
  /**
   * @generated from field: uint32 bet_amount = 1;
   */
  betAmount: number;
};

/**
 * Describes the message bastionpb.BuyFgRequest.
 * Use `create(BuyFgRequestSchema)` to create a new message.
 */
export const BuyFgRequestSchema: GenMessage<BuyFgRequest> = /*@__PURE__*/
  messageDesc(file_bastionpb_bastion, 4);

/**
 * @generated from message bastionpb.BuyFgResp
 */
export type BuyFgResp = Message<"bastionpb.BuyFgResp"> & {
  /**
   * @generated from field: repeated slotpb.Event events = 1;
   */
  events: Event[];
};

/**
 * Describes the message bastionpb.BuyFgResp.
 * Use `create(BuyFgRespSchema)` to create a new message.
 */
export const BuyFgRespSchema: GenMessage<BuyFgResp> = /*@__PURE__*/
  messageDesc(file_bastionpb_bastion, 5);

/**
 * @generated from message bastionpb.WSError
 */
export type WSError = Message<"bastionpb.WSError"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message bastionpb.WSError.
 * Use `create(WSErrorSchema)` to create a new message.
 */
export const WSErrorSchema: GenMessage<WSError> = /*@__PURE__*/
  messageDesc(file_bastionpb_bastion, 6);

